# Generated by Django 4.2.1 on 2023-06-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='imagen',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='detalle',
            name='nombre',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
