# Generated by Django 4.2.1 on 2023-06-24 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detalle_estado_alter_detalle_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 24, 3, 44, 4, 181081)),
        ),
    ]
