# Generated by Django 4.2.1 on 2023-07-04 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_detalle_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 7, 4, 1, 23, 30, 119437)),
        ),
    ]
