# Generated by Django 4.2.1 on 2023-07-05 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_detalle_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 3, 43, 27, 940834)),
        ),
    ]
